# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

[[main]]
  name = "Home"
  url = "#about"
  weight = 10

[[main]]
  name = "People"
  url = "people"
  weight = 15

[[main]]
  name = "Research"
  url = "research"
  weight = 16

[[main]]
  name = "Publications"
  url = "https://www.ncbi.nlm.nih.gov/myncbi/1BiLmrlnjqUQE/bibliography/public/?sortby=pubDate&sdirection=descending"
  weight = 20

[[main]]
  name = "Software"
  url = "software"
  weight = 30

[[main]]
  name = "Positions"
  url = "positions"
  weight = 40

[[main]]
  name = "Contact"
  url = "#contact"
  weight = 50

[[main]]
  name = "News"
  url = "news/_index.md"
  weight = 60


# Link to a PDF of your resume/CV from the menu.
# To enable, copy your resume/CV to `static/files/cv.pdf` and uncomment the lines below.
# [[main]]
#    name = "CV"
#    url = "files/cv.pdf"
#    weight = 70
